feat: implement CallCallablePoint to VM
line/wasmvm pull request #97
Opened 2023-03-20 01:17 UTC by loloicci

# Description

This PR implements CallCallablePoint to VM.
This calls a callable point (dynamic linked callee function).

## Types of changes

- [ ] Bug fix (changes which fixes an issue)
- [x] New feature (changes which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] ETC (build, ci, docs, perf, refactor, style, test)

## Checklist

- [x] I followed the [contributing guidelines](https://github.com/line/wasmvm/blob/main/CONTRIBUTING.md).
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] The PR title and commits are followed [conventional commit form](https://www.conventionalcommits.org/en/v1.0.0).

2023-03-23 08:28 UTC, loloicci commented on libwasmvm/src/calls.rs
> +
check readonly or read-write

2023-04-04 05:47 UTC, kokeshiM0chi approved these changes

2023-04-04 07:37 UTC, kokeshiM0chi commented on api/lib_test.go
> +	res, eventsData, attributesData, cost, err = CallCallablePoint(nameBin, cache, checksum, false, emptyBin, env, argsEvBin, &igasMeter2, store, api, &querier, TESTING_GAS_LIMIT, TESTING_PRINT_DEBUG)
Would you like to add a test case when the argument `isReadonly` = true?

2023-04-04 08:00 UTC, da1suk8 commented on api/lib.go
> +// returned used_gas: without instantiation cost
Does `used_gas` refer to the name of the variable? If so, isn't it `gasUsed`?

2023-04-04 13:27 UTC, dudong2 approved these changes

2023-04-06 07:14 UTC, kokeshiM0chi requested changes
Would you like to add a test case when the argument isReadonly = true?
This has been addressed [here](https://github.com/line/wasmvm/pull/97/files#diff-41f47570e26c8c3ff485fb26d89e5fb3c5468799c6b07fe3449dd2415730fd42R1521). Thanks.

2023-04-12 02:03 UTC, kokeshiM0chi approved these changes

2023-04-12 02:11 UTC, da1suk8 approved these changes

2023-04-12 08:29 UTC, loloicci commented
Cannot merge into dynamic_link because of https://github.com/line/wasmvm/issues/102.
All changes in this PR are included in https://github.com/line/wasmvm/pull/103.

2023-04-12 08:29 UTC, closed without merging