feat: Implement "ValidateDynamicLinkInterface" to vm
line/wasmvm pull request #99
Opened 2023-03-22 07:58 UTC by loloicci

# Description
This PR uses https://github.com/line/cosmwasm/pull/272 so updated after it is merged.

This PR implements `ValidateDynamicLinkInterface` to VM.
This is a part of https://github.com/line/cosmwasm/issues/273.

## Types of changes

- [ ] Bug fix (changes which fixes an issue)
- [x] New feature (changes which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] ETC (build, ci, docs, perf, refactor, style, test)

## Checklist

- [x] I followed the [contributing guidelines](https://github.com/line/wasmvm/blob/main/CONTRIBUTING.md).
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] The PR title and commits are followed [conventional commit form](https://www.conventionalcommits.org/en/v1.0.0).

2023-04-11 06:37 UTC, kokeshiM0chi requested changes
Please also test when the argument `isReadOnly=true` of `vm.CallCallablePoint()`.

2023-04-11 08:11 UTC, da1suk8 approved these changes

2023-04-11 09:24 UTC, kokeshiM0chi approved these changes

2023-04-12 08:28 UTC, loloicci commented
Cannot merge into dynamic_link because of https://github.com/line/wasmvm/issues/102.
All changes in this PR are included in https://github.com/line/wasmvm/pull/103.

2023-04-12 08:28 UTC, closed without merging